### ISSUE TITLE
Assignment 5 Completed 

### ISSUE THREAD

**Issue by emilykschwabe** [emilykschwabe/Assignment-5#1]
Hi Mark, 

I had fun playing through a couple of graphic designs. I tried a violin and box plot. Both were a little funky with the data, but still, look really neat.  I also made more detailed scatter plots following some of your recommendations. I hope it all looks alright to you Thanks. 

-Emily

**Comment by mdscheuerell** [comment]
Nice job, Emily! One suggestion I have would be to reduce the label size on the x-axis so it's easier to see the size breaks, but you don't need to do that here.
